-- =============================================================
-- PLAY ROOM ARTICHOKE — protecție anti-spam pentru formulare
-- Rulați integral în Supabase Dashboard → SQL Editor.
-- Necesită ca supabase_schema.sql și supabase_table_ordering.sql să fie rulate.
-- =============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.security_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action      TEXT NOT NULL CHECK (action IN ('table_order', 'contact', 'reservation')),
  outcome     TEXT NOT NULL CHECK (outcome IN ('accepted', 'blocked', 'turnstile_pass', 'turnstile_failed')),
  reason      TEXT NOT NULL DEFAULT '',
  ip_hash     TEXT NOT NULL CHECK (char_length(ip_hash) = 64),
  device_hash TEXT NOT NULL CHECK (char_length(device_hash) = 64),
  scope_hash  TEXT CHECK (scope_hash IS NULL OR char_length(scope_hash) = 64),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_security_events_action_created
  ON public.security_events(action, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_security_events_ip_created
  ON public.security_events(ip_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_security_events_device_created
  ON public.security_events(device_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_security_events_scope_created
  ON public.security_events(scope_hash, created_at DESC)
  WHERE scope_hash IS NOT NULL;

ALTER TABLE public.security_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.security_events FROM PUBLIC, anon, authenticated;

DROP POLICY IF EXISTS security_events_admin_select ON public.security_events;
CREATE POLICY security_events_admin_select
  ON public.security_events
  FOR SELECT
  TO authenticated
  USING (private.is_admin());

GRANT SELECT ON TABLE public.security_events TO authenticated;

CREATE OR REPLACE FUNCTION public.record_security_event(
  p_action TEXT,
  p_outcome TEXT,
  p_reason TEXT,
  p_ip_hash TEXT,
  p_device_hash TEXT,
  p_scope_hash TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Service role required';
  END IF;

  IF p_action NOT IN ('table_order', 'contact', 'reservation')
    OR p_outcome NOT IN ('accepted', 'blocked', 'turnstile_pass', 'turnstile_failed')
    OR p_ip_hash !~ '^[0-9a-f]{64}$'
    OR p_device_hash !~ '^[0-9a-f]{64}$'
    OR (p_scope_hash IS NOT NULL AND p_scope_hash !~ '^[0-9a-f]{64}$') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Invalid security event';
  END IF;

  INSERT INTO public.security_events (
    action, outcome, reason, ip_hash, device_hash, scope_hash
  ) VALUES (
    p_action,
    p_outcome,
    pg_catalog.left(COALESCE(p_reason, ''), 100),
    p_ip_hash,
    p_device_hash,
    p_scope_hash
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.has_recent_turnstile(
  p_action TEXT,
  p_device_hash TEXT,
  p_scope_hash TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Service role required';
  END IF;

  RETURN EXISTS (
    SELECT 1
    FROM public.security_events
    WHERE action = p_action
      AND outcome = 'turnstile_pass'
      AND device_hash = p_device_hash
      AND scope_hash = p_scope_hash
      AND created_at >= now() - INTERVAL '2 hours'
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.check_public_submission_limit(
  p_action TEXT,
  p_ip_hash TEXT,
  p_device_hash TEXT,
  p_scope_hash TEXT DEFAULT NULL
)
RETURNS TABLE (allowed BOOLEAN, reason TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_reason TEXT;
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Service role required';
  END IF;

  IF p_action NOT IN ('table_order', 'contact', 'reservation')
    OR p_ip_hash !~ '^[0-9a-f]{64}$'
    OR p_device_hash !~ '^[0-9a-f]{64}$'
    OR (p_scope_hash IS NOT NULL AND p_scope_hash !~ '^[0-9a-f]{64}$') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Invalid rate limit input';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      p_action || ':' || p_ip_hash || ':' || p_device_hash || ':' || COALESCE(p_scope_hash, ''),
      94127
    )
  );

  IF p_action = 'table_order' THEN
    IF p_scope_hash IS NULL THEN
      v_reason := 'invalid_scope';
    ELSIF (SELECT count(*) FROM public.security_events
           WHERE action = p_action AND outcome = 'accepted'
             AND scope_hash = p_scope_hash
             AND created_at >= now() - INTERVAL '1 hour') >= 20 THEN
      v_reason := 'qr_hour_limit';
    ELSIF (SELECT count(*) FROM public.security_events
           WHERE action = p_action AND outcome = 'accepted'
             AND ip_hash = p_ip_hash
             AND created_at >= now() - INTERVAL '1 hour') >= 30 THEN
      v_reason := 'ip_hour_limit';
    ELSIF (SELECT count(*) FROM public.security_events
           WHERE action = p_action AND outcome = 'accepted'
             AND device_hash = p_device_hash
             AND scope_hash = p_scope_hash
             AND created_at >= now() - INTERVAL '1 hour') >= 6 THEN
      v_reason := 'device_hour_limit';
    ELSIF (SELECT count(*) FROM public.security_events
           WHERE action = p_action AND outcome = 'accepted'
             AND ip_hash = p_ip_hash
             AND created_at >= now() - INTERVAL '5 minutes') >= 8 THEN
      v_reason := 'ip_burst_limit';
    END IF;
  ELSIF p_action = 'contact' THEN
    IF (SELECT count(*) FROM public.security_events
        WHERE action = p_action AND outcome = 'accepted'
          AND ip_hash = p_ip_hash
          AND created_at >= now() - INTERVAL '1 hour') >= 5 THEN
      v_reason := 'ip_hour_limit';
    ELSIF (SELECT count(*) FROM public.security_events
           WHERE action = p_action AND outcome = 'accepted'
             AND device_hash = p_device_hash
             AND created_at >= now() - INTERVAL '1 hour') >= 3 THEN
      v_reason := 'device_hour_limit';
    END IF;
  ELSE
    IF (SELECT count(*) FROM public.security_events
        WHERE action = p_action AND outcome = 'accepted'
          AND ip_hash = p_ip_hash
          AND created_at >= now() - INTERVAL '24 hours') >= 5 THEN
      v_reason := 'ip_day_limit';
    ELSIF (SELECT count(*) FROM public.security_events
           WHERE action = p_action AND outcome = 'accepted'
             AND device_hash = p_device_hash
             AND created_at >= now() - INTERVAL '24 hours') >= 3 THEN
      v_reason := 'device_day_limit';
    END IF;
  END IF;

  INSERT INTO public.security_events (
    action, outcome, reason, ip_hash, device_hash, scope_hash
  ) VALUES (
    p_action,
    CASE WHEN v_reason IS NULL THEN 'accepted' ELSE 'blocked' END,
    COALESCE(v_reason, ''),
    p_ip_hash,
    p_device_hash,
    p_scope_hash
  );

  RETURN QUERY SELECT v_reason IS NULL, COALESCE(v_reason, '');
END;
$$;

REVOKE ALL ON FUNCTION public.record_security_event(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.has_recent_turnstile(TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.check_public_submission_limit(TEXT, TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.record_security_event(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.has_recent_turnstile(TEXT, TEXT, TEXT)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.check_public_submission_limit(TEXT, TEXT, TEXT, TEXT)
  TO service_role;

-- Formularele publice sunt acceptate numai prin ruta serverului Next.js.
REVOKE EXECUTE ON FUNCTION public.submit_contact_message(TEXT, TEXT, TEXT, TEXT)
  FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_reservation(TEXT, TEXT, DATE, TIME, INTEGER, INTEGER, TEXT)
  FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_table_order(UUID, UUID, JSONB, TEXT)
  FROM anon, authenticated;

GRANT EXECUTE ON FUNCTION public.submit_contact_message(TEXT, TEXT, TEXT, TEXT)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.submit_reservation(TEXT, TEXT, DATE, TIME, INTEGER, INTEGER, TEXT)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.submit_table_order(UUID, UUID, JSONB, TEXT)
  TO service_role;

COMMIT;
