-- =============================================================
-- PLAY ROOM ARTICHOKE — jurnal imuabil al acțiunilor administrative
-- Rulați integral în Supabase Dashboard → SQL Editor.
-- =============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id UUID,
  actor_email   TEXT,
  action        TEXT NOT NULL,
  entity_type   TEXT NOT NULL,
  entity_id     TEXT NOT NULL,
  old_value     JSONB,
  new_value     JSONB,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created
  ON public.admin_audit_log(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_entity
  ON public.admin_audit_log(entity_type, entity_id, created_at DESC);

ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.admin_audit_log FROM PUBLIC, anon, authenticated;

DROP POLICY IF EXISTS admin_audit_log_admin_select ON public.admin_audit_log;
CREATE POLICY admin_audit_log_admin_select
  ON public.admin_audit_log
  FOR SELECT
  TO authenticated
  USING (private.is_admin());

GRANT SELECT ON TABLE public.admin_audit_log TO authenticated;

CREATE OR REPLACE FUNCTION private.capture_admin_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_actor_user_id UUID := auth.uid();
  v_actor_email TEXT := NULLIF((auth.jwt() ->> 'email'), '');
  v_action TEXT;
  v_entity_id TEXT;
  v_old_value JSONB;
  v_new_value JSONB;
BEGIN
  IF TG_TABLE_NAME = 'products' THEN
    v_entity_id := NEW.id;
    IF TG_OP = 'INSERT' THEN
      v_action := 'product_created';
      v_new_value := pg_catalog.jsonb_build_object(
        'name', NEW.name,
        'price', NEW.price,
        'active', NEW.active,
        'category', NEW.category
      );
    ELSE
      IF ROW(OLD.name, OLD.price, OLD.active, OLD.category, OLD.description, OLD.image)
        IS NOT DISTINCT FROM
        ROW(NEW.name, NEW.price, NEW.active, NEW.category, NEW.description, NEW.image) THEN
        RETURN NEW;
      END IF;

      v_action := CASE
        WHEN OLD.price IS DISTINCT FROM NEW.price THEN 'product_price_changed'
        ELSE 'product_updated'
      END;
      v_old_value := pg_catalog.jsonb_build_object(
        'name', OLD.name,
        'price', OLD.price,
        'active', OLD.active,
        'category', OLD.category
      );
      v_new_value := pg_catalog.jsonb_build_object(
        'name', NEW.name,
        'price', NEW.price,
        'active', NEW.active,
        'category', NEW.category
      );
    END IF;
  ELSIF TG_TABLE_NAME = 'orders' THEN
    IF OLD.status IS NOT DISTINCT FROM NEW.status THEN
      RETURN NEW;
    END IF;
    v_action := 'order_status_changed';
    v_entity_id := NEW.id::TEXT;
    v_old_value := pg_catalog.jsonb_build_object(
      'order_number', OLD.order_number,
      'status', OLD.status
    );
    v_new_value := pg_catalog.jsonb_build_object(
      'order_number', NEW.order_number,
      'status', NEW.status
    );
  ELSIF TG_TABLE_NAME = 'table_sessions' THEN
    v_entity_id := NEW.id::TEXT;
    IF TG_OP = 'INSERT' THEN
      v_action := 'table_opened';
      v_actor_user_id := COALESCE(v_actor_user_id, NEW.opened_by);
      v_new_value := pg_catalog.jsonb_build_object(
        'table_number', NEW.table_number,
        'opened_at', NEW.opened_at,
        'expires_at', NEW.expires_at
      );
    ELSIF OLD.status = 'active' AND NEW.status = 'closed' THEN
      IF NEW.closed_at IS NOT NULL
        AND OLD.expires_at IS NOT NULL
        AND NEW.closed_at = OLD.expires_at
        AND OLD.expires_at <= now() THEN
        v_action := 'table_expired';
        v_actor_user_id := NULL;
        v_actor_email := NULL;
      ELSE
        v_action := 'table_closed';
      END IF;
      v_old_value := pg_catalog.jsonb_build_object(
        'table_number', OLD.table_number,
        'status', OLD.status,
        'opened_at', OLD.opened_at
      );
      v_new_value := pg_catalog.jsonb_build_object(
        'table_number', NEW.table_number,
        'status', NEW.status,
        'closed_at', NEW.closed_at
      );
    ELSIF OLD.token IS DISTINCT FROM NEW.token THEN
      v_action := 'table_qr_rotated';
      v_old_value := pg_catalog.jsonb_build_object(
        'table_number', OLD.table_number,
        'expires_at', OLD.expires_at,
        'qr_replaced', TRUE
      );
      v_new_value := pg_catalog.jsonb_build_object(
        'table_number', NEW.table_number,
        'expires_at', NEW.expires_at,
        'qr_replaced', TRUE
      );
    ELSE
      RETURN NEW;
    END IF;
  ELSE
    RETURN NEW;
  END IF;

  INSERT INTO public.admin_audit_log (
    actor_user_id,
    actor_email,
    action,
    entity_type,
    entity_id,
    old_value,
    new_value
  ) VALUES (
    v_actor_user_id,
    v_actor_email,
    v_action,
    TG_TABLE_NAME,
    v_entity_id,
    v_old_value,
    v_new_value
  );

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.capture_admin_audit() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS products_admin_audit ON public.products;
CREATE TRIGGER products_admin_audit
  AFTER INSERT OR UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION private.capture_admin_audit();

DROP TRIGGER IF EXISTS orders_admin_audit ON public.orders;
CREATE TRIGGER orders_admin_audit
  AFTER UPDATE OF status ON public.orders
  FOR EACH ROW EXECUTE FUNCTION private.capture_admin_audit();

DROP TRIGGER IF EXISTS table_sessions_admin_audit ON public.table_sessions;
CREATE TRIGGER table_sessions_admin_audit
  AFTER INSERT OR UPDATE ON public.table_sessions
  FOR EACH ROW EXECUTE FUNCTION private.capture_admin_audit();

COMMIT;
