-- =============================================================
-- PLAY ROOM ARTICHOKE — limitarea încercărilor de autentificare
-- Rulați integral în Supabase Dashboard → SQL Editor.
-- =============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS private.admin_login_attempts (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash     TEXT NOT NULL CHECK (char_length(ip_hash) = 64),
  device_hash TEXT NOT NULL CHECK (char_length(device_hash) = 64),
  successful  BOOLEAN NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_login_attempts_ip_created
  ON private.admin_login_attempts(ip_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_login_attempts_device_created
  ON private.admin_login_attempts(device_hash, created_at DESC);

ALTER TABLE private.admin_login_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE private.admin_login_attempts FROM PUBLIC, anon, authenticated;

DROP FUNCTION IF EXISTS public.check_admin_login_allowed(TEXT, TEXT);

CREATE OR REPLACE FUNCTION public.begin_admin_login_attempt(
  p_ip_hash TEXT,
  p_device_hash TEXT,
  p_turnstile_verified BOOLEAN
)
RETURNS TABLE (
  allowed BOOLEAN,
  challenge_required BOOLEAN,
  retry_after_seconds INTEGER,
  failure_count INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_last_success TIMESTAMPTZ;
  v_latest_failure TIMESTAMPTZ;
  v_failure_count INTEGER;
  v_unlock_at TIMESTAMPTZ;
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Service role required';
  END IF;

  IF p_ip_hash !~ '^[0-9a-f]{64}$' OR p_device_hash !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Invalid login limit input';
  END IF;

  -- Două blocări separate împiedică ocolirea limitei prin cereri paralele
  -- cu același IP și identificatori de dispozitiv diferiți.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('ip:' || p_ip_hash, 52741)
  );
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('device:' || p_device_hash, 52741)
  );

  SELECT max(created_at)
  INTO v_last_success
  FROM private.admin_login_attempts
  WHERE successful = TRUE
    AND (ip_hash = p_ip_hash OR device_hash = p_device_hash);

  SELECT count(*)::INTEGER, max(created_at)
  INTO v_failure_count, v_latest_failure
  FROM private.admin_login_attempts
  WHERE successful = FALSE
    AND (ip_hash = p_ip_hash OR device_hash = p_device_hash)
    AND created_at >= now() - INTERVAL '30 minutes'
    AND created_at > COALESCE(v_last_success, '-infinity'::TIMESTAMPTZ);

  IF v_failure_count >= 5 THEN
    v_unlock_at := v_latest_failure + INTERVAL '30 minutes';
    RETURN QUERY SELECT
      FALSE,
      FALSE,
      GREATEST(1, pg_catalog.ceil(EXTRACT(EPOCH FROM (v_unlock_at - now())))::INTEGER),
      v_failure_count;
    RETURN;
  END IF;

  IF v_failure_count >= 2 AND NOT COALESCE(p_turnstile_verified, FALSE) THEN
    RETURN QUERY SELECT FALSE, TRUE, 0, v_failure_count;
    RETURN;
  END IF;

  -- Rezervă atomic încercarea înainte ca serverul să verifice parola.
  -- O autentificare reușită adaugă imediat un eveniment successful care
  -- resetează seria de eșecuri pentru următoarea încercare.
  INSERT INTO private.admin_login_attempts (ip_hash, device_hash, successful)
  VALUES (p_ip_hash, p_device_hash, FALSE);

  RETURN QUERY SELECT TRUE, FALSE, 0, v_failure_count + 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_admin_login_attempt(
  p_ip_hash TEXT,
  p_device_hash TEXT,
  p_successful BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Service role required';
  END IF;

  IF p_ip_hash !~ '^[0-9a-f]{64}$'
    OR p_device_hash !~ '^[0-9a-f]{64}$'
    OR p_successful IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Invalid login attempt';
  END IF;

  INSERT INTO private.admin_login_attempts (ip_hash, device_hash, successful)
  VALUES (p_ip_hash, p_device_hash, p_successful);

  DELETE FROM private.admin_login_attempts
  WHERE created_at < now() - INTERVAL '90 days';
END;
$$;

REVOKE ALL ON FUNCTION public.begin_admin_login_attempt(TEXT, TEXT, BOOLEAN)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_admin_login_attempt(TEXT, TEXT, BOOLEAN)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.begin_admin_login_attempt(TEXT, TEXT, BOOLEAN)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.record_admin_login_attempt(TEXT, TEXT, BOOLEAN)
  TO service_role;

COMMIT;
